# Para uso local, você precisa configurar estas credenciais
# Para produção no Streamlit Cloud, configure no painel de secrets

# Exemplo de configuração para Google Sheets API
[gcp_service_account]
type = "service_account"
project_id = "quadra-financeiro"
private_key_id = "d851d0c3e705f218d2e7d688ac023997289ef5fe"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDSsu17pvrlSYe1
B4s0O/Z6z6qQ+d/i8akRce1Jbuy0i2ufzHT0vA55MDh77OIYXB5mhNUZDWMkAKBz
C3q7PpvyYrnWWYXCVbckJmkuwcEpZ+hMqA4WBpuBcOgB4Ohcz34/gKBfLa6w8lyS
wM6Lm+A2gm1cNYZk7i22PUGGMtW6OXzglvoLkIQfqZW3nS/fz+8ArbV7MBDIa0Mt
qJtSj+dNJ5a56gUo2Nt1D4zoQO3d9cH79ahJSOqr4yTqKWkmIhf+k1gRy/XaAHYX
5iOBrj6vfePWiuStNI9TDUuCDNC8T2RuIxwfCNthNKHYhz929adygeKuVqiJ+cp1
anFhv6O1AgMBAAECggEAHNdnULTTxU0iaXJl6LmIjNkeZQf/UKZ52Sx6KcIoXrJz
AgXPwKx5YrdqE/SiImmBs9DdBrfhaU04qWbZ3wW7/Rrsi13nxGlNT4J+hWr6UPur
PcsHWpZ+9OIKsC8kP4gbpP+rdDvhnNEgQOppm4yzzWJfK+8bvXcpBLgv3vnYbcwu
4NC9CzmlIkK0GQZztEKcm05SnATJaGozInmwAf/SWb4QQd8RhhuehMOencteEYTU
lEHASXBOInzHvpIyDVZ0aUGCsfI9UMiH+QzrIoE+fvRYZF9vqPg6f56eWE6bNsNA
wuW5UgIcjw8JLc5HAq5Pv9g2oabMQwS0T8CwXBDBoQKBgQD/RhvPar6IfRZzr1ji
RiRAaROsotUrhnOALM7HffkdFGN6/Cq+up8xpwuM4t2w3owWsEKzSNL2A85Q7bVl
WJhL5clcBz/tcOin4xd0n2CW0dfObF30nU5FZ1EALOPQbroqY2FPfGtRRWmC3wjp
iw0XSSR4Wt48FqXeCL1SizZzLQKBgQDTTFwCQA/s2xwnjCzEsNyY4NtMuTXmc1GF
hEQcm298PoTB8GPVTqjv9v1tBKy5MPu+f4pOQhsqQPtWpO8LxyG0Im/A/IJLYoFl
qS6PZXIgDjGWlBm0CdpgLv4SWPxFELOTEj+Nk9I64v0yEehahF6FMvuUOKmYJRxL
84oLyGDnqQKBgBO1kggdscBQCB++dhpiWAIxGrfFirfllZ1b2EtGyqkYHeYs+g/n
0MrAnv+ttHgndqF50myNPtyHxrIw6ER+5qNVhop4dNMcWJo9yl3SwF5krUjezRJJ
4vUw2OwuixhYtD75lVXRwWdw+IiGN+XwOn6Fwy8XtPjmtr/B5Pwui3GxAoGBAJJG
RVfFc4DbumTiVEehzEUFPKujd93eLSxKAUDwlcAkI5GC0gnj122vxYcH+m6Fq3EY
J+2/M8EPlS9JJLc5lmp2gHjQFX8MZVm0QihA6T2ptchxJE4PmB6HyZl4AsPpKPeC
ZX6kO6BKbU+ROBIZmrmJLsJQa4+I+UrXANThVbxpAoGAOeSlLgllcgo8vU8rEd2Z
/PZqvZMC1oktsHDnzZhuhMCOStp0yDoxnIhcLMWoe6uvTYRf/BEHz/GkrP/gUO72
L2mkikKyDk2DUvUd0sZcx7bKG5El/GyxaZlizogwIwa0gbr6YDPMjZZW4J+otbzu
2DAYLFaEmpEr7iVd2/shShQ=
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheets-access@quadra-financeiro.iam.gserviceaccount.com"
client_id = "108441070455114002161"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets-access%40quadra-financeiro.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# Nome da spreadsheet no Google Sheets
spreadsheet_name = "Quadra Financeiro"